package com.zdy.ssm.mapper;

import com.zdy.ssm.bean.Dept;
import com.zdy.ssm.bean.DeptExample;
import com.zdy.ssm.bean.Emp;
import com.zdy.ssm.bean.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int countByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int deleteByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int insertSelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    List<Emp> selectByExample(EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    Emp selectByPrimaryKey(Integer empId);

    /**
     * --------------------------------------------------------
     * 自定义修改，添加部门信息的查询
     * This method corresponds to the database table tbl_dept
     */
    List<Emp> selectByExampleWithDept(EmpExample example);

    /**
     * --------------------------------------------------------
     * 自定义修改，添加部门信息的查询
     * This method corresponds to the database table tbl_dept
     */
    Emp selectByPrimaryKeyWithDept(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int updateByExampleSelective(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int updateByExample(@Param("record") Emp record, @Param("example") EmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int updateByPrimaryKeySelective(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbggenerated Thu Aug 31 11:31:32 CST 2023
     */
    int updateByPrimaryKey(Emp record);
}